### PR TITLE
Fix the timing in creating objects

### PR DESCRIPTION
**Pull request by loayalsaid1**

### CODE REVIEW

**Comment by iygeal** [comment]
What specifically does these changes do?

**Comment by loayalsaid1** [comment]
## Changing the init function in the base model
Refactored it with with the one from the old code base I made..

specifically.. The change is making  the created_at == updated_at so when you test it gives you the same time 

but making both equal to datetime.now() will  still make a difference in some milliseconds I believe


Nice first comment to me!

**Comment by iygeal** [comment]
OK. Merged!

**Comment by loayalsaid1** [comment]
This is when you create the object for the first time

**Pull request merged**
